version: '3'
services:
      client:
            restart: always
            build: ./
            ports:
                  - "80:3000"
            depends_on:
                - api
            links:
                  - api
      api:
            container_name: backend
            restart: always
            build: ./backend
            ports:
                  - '4000:4000'
            links:
                  - mongodb
      mongodb:
            container_name: memes
            image: mongo
            restart: always
            container_name: mongodb
            ports:
                  - '27017:27017'
